name = "typing"
type = "javascript"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./.output/public"
entry-point = "./.output"

[build]
# See: https://github.com/nuxt/framework/issues/1239
#command = "NITRO_PRESET=cloudflare yarn run build"
command = "true"
upload.format = "service-worker"
