name: Deploy

on:
  push:
    branches:
      - main
      - feature/deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
        working-directory: nuxt
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v1
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'nuxt'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
