name: Deploy

on:
  push:
    branches:
      - main
      - feature/deploy

jobs:
  deploy:
    name: Deploy


    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        node: [16]


    steps:
      #- name: Use Node.js
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: '16'

      - uses: actions/checkout@v2

      - name: Install
        run: yarn install
        working-directory: nuxt

      - name: Build
        run: yarn run build
        working-directory: nuxt
        env:
          NITRO_PRESET: cloudflare

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'nuxt'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
