name: Deploy

on:
  push:
    branches:
      - main
      - feature/deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          working-directory: ./nuxt
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
